### ISSUE TITLE
[Genmodel Editor] IndexOutOfBoundsException when adding entries to tables

### ISSUE THREAD

**Issue by MWEclipse** [MWEclipse/testing#124]
| --- | --- |
| Bugzilla Link | [495185](https://bugs.eclipse.org/bugs/show_bug.cgi?id=495185) |
| Status | NEW |
| Importance | P1 normal |
| Reported | Jun 01, 2016 11:13 EDT |
| Modified | Aug 19, 2023 11:37 EDT |
| Version | 1.8.0 |
| Reporter | Stefan Dirix |

## Description 
Various tables in the Genmodel Editor throw IndexOutOfBoundsException.

When the "Plus" button is clicked an entry is added to the table (without any label, only visible by clicking on it). Only 2-6 entries (depends on each table) can be added. After that additional entries are showed very shortly but vanish immediately. In the problem log an IndexOutOfBoundsException is visible.

* Root View > Edit > Edit Plug-in Variables
* Root View > Editor > Editor Plug-in Variables
* Root View > Model > Model Plug-in Variables
* Root View > Model Class Defaults > Static Packages
* Root View > Templates & Merge > Template Plug-in Variables
* Root View > Tests > Tests Plug-in Variables
* EAttribute View > Property Filter Flags

The StackTrace:

org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=4, size=4\
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)\
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)\
	at org.eclipse.core.internal.databinding.property.list.SimplePropertyObservableList.set(SimplePropertyObservableList.java:450)\
	at org.eclipse.core.databinding.observable.list.DecoratingObservableList.set(DecoratingObservableList.java:224)\
	at org.eclipse.emf.ecp.edit.internal.swt.util.ECPObservableValue.doSetValue(ECPObservableValue.java:71)\
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.setValue(AbstractObservableValue.java:66)\
	at org.eclipse.core.databinding.UpdateValueStrategy.doSet(UpdateValueStrategy.java:469)\
	at org.eclipse.core.databinding.ValueBinding$3$1.run(ValueBinding.java:206)\
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:149)\
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)\
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:153)\
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:171)\
	at org.eclipse.core.databinding.ValueBinding$3.run(ValueBinding.java:196)\
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:149)\
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)\
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:153)\
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:171)\
	at org.eclipse.core.databinding.ValueBinding.doUpdate(ValueBinding.java:158)\
	at org.eclipse.core.databinding.ValueBinding.updateTargetToModel(ValueBinding.java:118)\
	at org.eclipse.emfforms.spi.view.control.multiattribute.MultiAttributeSWTRenderer$ECPListEditingSupport.saveCellEditorValue(MultiAttributeSWTRenderer.java:718)\
	at org.eclipse.jface.viewers.ColumnViewerEditor.saveEditorValue(ColumnViewerEditor.java:453)\
	at org.eclipse.jface.viewers.ColumnViewerEditor.applyEditorValue(ColumnViewerEditor.java:309)\
	at org.eclipse.jface.viewers.ColumnViewerEditor$1.applyEditorValue(ColumnViewerEditor.java:152)\
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:336)\
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)\
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)\
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)\
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:333)\
	at org.eclipse.jface.viewers.CellEditor.focusLost(CellEditor.java:722)\
	at org.eclipse.jface.viewers.TextCellEditor$4.focusLost(TextCellEditor.java:184)\
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:144)\
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)\
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5208)\
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)\
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)\
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1345)\
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:4062)\
	at org.eclipse.swt.widgets.Control.gtk_event_after(Control.java:3334)\
	at org.eclipse.swt.widgets.Text.gtk_event_after(Text.java:1674)\
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1986)\
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5820)\
	at org.eclipse.swt.widgets.Text.windowProc(Text.java:2894)\
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5479)\
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)\
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)\
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)\
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)\
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)\
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4130)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1119)\
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1020)\
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)\
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)\
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)\
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)\
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)\
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)\
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)\
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)\
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)\
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)\
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)\
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\
	at java.lang.reflect.Method.invoke(Method.java:498)\
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)\
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)\
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)\
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Jun 01, 2016 11:17

The MultiReferenceControlRenderer doesn't check the max size of the bounded list and thus allows to add more entries than possible

**Comment by MWEclipse** [comment]
By Stefan Dirix on Jun 01, 2016 11:49

But there should be no maximum number of entries. The 'classic' genmodel editor allows an arbitrary number of entries.

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Jun 01, 2016 11:54

org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=4, size=4\
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)\
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)\
I have to check this, but my interpretation of this stack is, that there is an unmodifiable list with the size 4 to which we try to add a 5th element

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Jun 02, 2016 02:56

I can't reproduce this error on windows. Can you please retest and give exact steps to reproduce?

**Comment by MWEclipse** [comment]
Aug 28, 2021 14:56

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.

**Comment by MWEclipse** [comment]
Aug 19, 2023 11:37

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.
