### ISSUE TITLE
Cannot create Index Domain Model Reference in Tooling and missing property descriptor

### ISSUE THREAD

**Issue by MWEclipse** [MWEclipse/testing#152]
| --- | --- |
| Bugzilla Link | [527065](https://bugs.eclipse.org/bugs/show_bug.cgi?id=527065) |
| Status | NEW |
| Importance | P3 normal |
| Reported | Nov 09, 2017 10:10 EDT |
| Modified | Oct 25, 2023 16:06 EDT |
| Version | 1.14.0 |
| Reporter | Lucas Koehler |

## Description 
Cannot create IndexDMR.\
Example was tried for User (of the make it happen model): Index Reference from user to its feature tasks.

Exception:\
java.lang.IllegalArgumentException: The given VDomainModelReference must not be null.\
at org.eclipse.emfforms.internal.core.services.databinding.EMFFormsDatabindingImpl.getBestDomainModelReferenceConverter(EMFFormsDatabindingImpl.java:174)\
at org.eclipse.emfforms.internal.core.services.databinding.EMFFormsDatabindingImpl.getValueProperty(EMFFormsDatabindingImpl.java:86)\
at org.eclipse.emfforms.internal.core.services.databinding.index.IndexDomainModelReferenceConverter.convertToValueProperty(IndexDomainModelReferenceConverter.java:171)\
at org.eclipse.emfforms.internal.core.services.databinding.EMFFormsDatabindingImpl.getValueProperty(EMFFormsDatabindingImpl.java:90)\
at org.eclipse.emfforms.internal.core.services.databinding.EMFFormsDatabindingImpl.getValueProperty(EMFFormsDatabindingImpl.java:1)\
at org.eclipse.emf.ecp.view.internal.editor.handler.CreateDomainModelReferenceWizard$CustomizeDomainModelReferencePage.isValueSet(CreateDomainModelReferenceWizard.java:379)\
at org.eclipse.emf.ecp.view.internal.editor.handler.CreateDomainModelReferenceWizard$CustomizeDomainModelReferencePage.access$0(CreateDomainModelReferenceWizard.java:362)\
at org.eclipse.emf.ecp.view.internal.editor.handler.CreateDomainModelReferenceWizard$CustomizeDomainModelReferencePage$1.notifyChanged(CreateDomainModelReferenceWizard.java:281)\
at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)\
at org.eclipse.emf.ecp.view.spi.model.impl.VFeaturePathDomainModelReferenceImpl.setDomainModelEFeature(VFeaturePathDomainModelReferenceImpl.java:180)\
at org.eclipse.emf.ecp.view.internal.editor.controls.LinkFeatureControlRenderer$FilteredReferenceCommand.setSelectedValues(LinkFeatureControlRenderer.java:128)\
at org.eclipse.emf.ecp.view.spi.editor.controls.AbstractFilteredReferenceCommand.doExecute(AbstractFilteredReferenceCommand.java:110)\
at org.eclipse.emf.edit.command.ChangeCommand.execute(ChangeCommand.java:130)

Throws an exception in the UI and also throws an exception that no item property descriptor was found: \
No IItemPropertyDescriptor for feature index in EClass IndexDomainModelReference found.

**Comment by MWEclipse** [comment]
Nov 13, 2019 15:27

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.

**Comment by MWEclipse** [comment]
Nov 03, 2021 08:35

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.

**Comment by MWEclipse** [comment]
Oct 25, 2023 16:06

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.
