### ISSUE TITLE
[Generic Editor] fails silently when a resource save fails

### ISSUE THREAD

**Issue by MWEclipse** [MWEclipse/testing#168]
| --- | --- |
| Bugzilla Link | [533629](https://bugs.eclipse.org/bugs/show_bug.cgi?id=533629) |
| Status | NEW |
| Importance | P3 normal |
| Reported | Apr 16, 2018 11:58 EDT |
| Modified | Nov 08, 2023 02:27 EDT |
| Reporter | Lucas Koehler |

## Description 
When saving a resource in the Generic Editor and one of the resources in the Generic Editor's ResourceSet has an unknown URI protocol, the save fails and throws an java.net.MalformedURLException.\
The issue seems to be that the ResourceSet's URIConverter has a URIHandler (probably some default one) that claims it can handle the URI but then fails when creating the OutputStream.

For instance with a Resoruce with URI protocol xyz.

java.net.MalformedURLException: unknown protocol: xyz\
	at java.net.URL.<init>(URL.java:600)\
	at java.net.URL.<init>(URL.java:490)\
	at java.net.URL.<init>(URL.java:439)\
	at org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createOutputStream(URIHandlerImpl.java:110)\
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createOutputStream(ExtensibleURIConverterImpl.java:349)\
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:996)\
	at org.eclipse.emfforms.spi.editor.helpers.ResourceSetHelpers.save(ResourceSetHelpers.java:64)\
	at org.eclipse.emfforms.spi.editor.GenericEditor.doSave(GenericEditor.java:153)\
	at org.eclipse.ui.internal.SaveableHelper.lambda$0(SaveableHelper.java:154)\
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)\
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)\
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)\
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)\
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)\
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)\
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)\
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:259)\
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:158)\
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3917)\
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3931)\
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:54)

**Comment by MWEclipse** [comment]
By Mat Hansen on May 17, 2018 04:11

It should be noted that the underlying problem is a bit broader. The GenericEditor iterates over all loaded resources whenever a save is requested. The save will only complete successfully (and therefore clean the dirty state of the editor) when all loaded resources could be saved. If a resource is loaded which cannot be saved i.e. because it is read-only or, like in this case, has an unknown URI protocol the save will fail silently. The symptom for this is that the dirty state does not vanish.

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Aug 22, 2018 09:35

Mass Move due to time constraints

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Nov 06, 2018 04:40

Mass move to 1.20 due to time constraints.

**Comment by MWEclipse** [comment]
Nov 17, 2021 19:33

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.

**Comment by MWEclipse** [comment]
Nov 08, 2023 02:27

This bug hasn't had any activity in quite some time. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.

If you have further information on the current state of the bug, please add it. The information can be, for example, that the problem still occurs, that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.

--\
The automated Eclipse Genie.
