### ISSUE TITLE
EMFForms Editor unable to open resource with custom content type and parser registered

### ISSUE THREAD

**Issue by MWEclipse** [MWEclipse/testing#195]
| --- | --- |
| Bugzilla Link | [552029](https://bugs.eclipse.org/bugs/show_bug.cgi?id=552029) |
| Status | NEW |
| Importance | P3 normal |
| Reported | Oct 11, 2019 04:51 EDT |
| Modified | Nov 07, 2022 07:33 EDT |
| Reporter | Grzegorz Abramczyk |

## Description 
I have custom content type defined and an org.eclipse.emf.ecore.content_parser defined for that type. 

The file opens correctly in generated editor but EMFForms Editor tries to use default XMI parser and fails - looking into stack trace it looks like ResourceSetImpl is passing null getFactory function but ResourceFactoryRegistryImpl is expecting UNSPECIFIED_CONTENT_TYPE = "" to activate content type resolution.

https://git.eclipse.org/c/emf/org.eclipse.emf.git/tree/plugins/org.eclipse.emf.ecore/src/org/eclipse/emf/ecore/resource/impl/ResourceSetImpl.java#n425\
https://git.eclipse.org/c/emf/org.eclipse.emf.git/tree/plugins/org.eclipse.emf.ecore/src/org/eclipse/emf/ecore/resource/impl/ResourceFactoryRegistryImpl.java#n121

Stack trace 

org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Content is not allowed in prolog.\
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:195)\
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)\
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)\
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)\
	at org.eclipse.emfforms.spi.editor.helpers.ResourceSetHelpers.addResourceToSet(ResourceSetHelpers.java:237)\
	at org.eclipse.emfforms.spi.editor.helpers.ResourceSetHelpers.loadResourceWithProxies(ResourceSetHelpers.java:159)\
	at org.eclipse.emfforms.spi.editor.GenericEditor.loadResource(GenericEditor.java:578)\
	at org.eclipse.emfforms.spi.editor.GenericEditor.init(GenericEditor.java:285)\
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:354)\
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:340)\
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)\
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)\
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1001)\
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:966)\
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)\
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:411)\
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:333)\
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)\
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)\
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)\
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)\
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1015)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:675)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:781)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:752)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:746)\
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:730)\
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:107)\
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)\
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)\
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:146)\
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:6018)\
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:219)\
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)\
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)\
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)\
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)\
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)\
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)\
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:132)\
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)\
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)\
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)\
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)\
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)\
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)\
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)\
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:652)\
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:616)\
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:791)\
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:404)\
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1240)\
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3209)\
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3114)\
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)\
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3112)\
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3083)\
	at org.eclipse.ui.actions.OpenWithMenu.openEditor(OpenWithMenu.java:326)\
	at org.eclipse.ui.actions.OpenWithMenu.lambda$0(OpenWithMenu.java:183)\
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)\
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)\
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)\
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)\
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)\
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)\
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)\
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)\
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)\
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)\
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)\
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)\
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)\
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)\
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)\
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)\
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)\
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)\
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)\
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)\
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)\
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)\
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)\
Caused by: org.xml.sax.SAXParseExceptionpublicId: platform:/resource/twx/DCS_2.0.19.1.twx; systemId: platform:/resource/twx/DCS_2.0.19.1.twx; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.\
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)\
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)\
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)\
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)\
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)\
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:978)\
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)\
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)\
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)\
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)\
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)\
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)\
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)\
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)\
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	... 90 more

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Nov 27, 2019 08:23

Hi Grzegorz, 

would you like to provide a contribution for this?

Best

**Comment by MWEclipse** [comment]
By Grzegorz Abramczyk on Nov 27, 2019 13:17

I will try to prepare a fix but I need a few days to set up dev env and finalize it.

**Comment by MWEclipse** [comment]
By Eugen Neufeld on Sep 18, 2020 06:28

Moving due to time constraints
